### ISSUE TITLE
Database for coding

### ISSUE THREAD

**Issue by minhson0506** [minhson0506/DatingApp-Hook#10]
When we start to code, it need a basic database

**Comment by thuymymai** [comment]
Database link: [https://docs.google.com/spreadsheets/d/1bRQ_3ECJXqgXvwp2NAnhK8MlRfqjjIUfrumBuatvMTA/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1bRQ_3ECJXqgXvwp2NAnhK8MlRfqjjIUfrumBuatvMTA/edit?usp=sharing)

**Comment by thuymymai** [comment]
Updated @minhson0506

**Comment by minhson0506** [comment]
ToDO: create tool for auto create Json for adding data

**Comment by minhson0506** [comment]
Finish tool for create json data.
@JulianCCY you should add chat data for testing chat screen

**Comment by thuymymai** [comment]
TODO: 
1. Clean database for each user.
2. Check again favourites & comment to add to excel.
3. Add preference_family
4. Check if we should use preference_distance or not?
5. Quizzes?
