### ISSUE TITLE
Profile screen

### ISSUE THREAD

**Issue by minhson0506** [minhson0506/DatingApp-Hook#12]
- Create profile screen
- Edit profile screen

**Comment by thuymymai** [comment]
![Screenshot 2022-02-18 at 0 05 56](https://user-images.githubusercontent.com/85672212/154578725-8b58197b-f104-45c6-b1be-abc05b7e5a7d.png)
Because we are using the same ListItem with the Home screen. It's showing the images with the same styling with home screen.
