### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by minhson0506** [minhson0506/DatingApp-Hook#14]
- Display randomly person can be matched with user. 
- User can see their profile by clicking image

**Comment by thuymymai** [comment]
Cannot display additiondata.interest[0] after reloading app. Before reload it works.
![Screenshot 2022-02-18 at 0 02 54](https://user-images.githubusercontent.com/85672212/154578332-ef026a4c-a215-49bc-9477-b02e75b6c159.png)
n

**Comment by minhson0506** [comment]
Fixed that error: missing await when try to parse json
