### ISSUE TITLE
Chat Screen

### ISSUE THREAD

**Issue by minhson0506** [minhson0506/DatingApp-Hook#15]
### New hooks 
- whoever likes one of the photos (avatar or not) from current users would be considered as new hooks
- show five most recent users who like your photos
### Message
- Message shows a list of messages with matched users, and then navigates to the chatroom
- the chatting process is based on the comment on a file

### complete chat first screen
- add none case if the current user doesn't have any new hooks and message
- show the newest message of each conversation (fixed bug)

### complete chat second screen
- only left the UI
- update screen for every 100 ms
- show all messages on the screen
- update screen right after receiving or sending a messages

#### complete chat screen first look:
- fetch single new hook
- fetch messages and show the most recent message on chat screen

#### complete chat screen second draft
- fetch multiple new hooks
- gaining new hooks data with filtering and combining object array, checking who liked our user photos,
- adding comment and do like function with postman

**Comment by JulianCCY** [comment]
complete chat screen first look
