### ISSUE TITLE
Interview

### ISSUE THREAD

**Issue by minhson0506** [minhson0506/DatingApp-Hook#2]
[ ] Create the list of interview question
[ ] Talk to the right person for interviewing
[ ] Summarize 

@JulianCCY 
@thuymymai

**Comment by thuymymai** [comment]
Questions for interview:

1. Have you ever used dating applications? Which one do you like the most?
2. What features in a dating application that you like/hate the most? Why?
3. What features do you expect to have in a dating application?
4. How can you define a person that would be a perfect match for you?
5. What criteria would you consider when choosing a partner?
6. What’s important to you when using a dating application? Information secure? Matching percentages?
7. Have  you ever experienced any funny/embarrassing situations when using a dating application? If yes, How and Why?  
8. Which types of relationship are you looking for?
Link to form: [https://docs.google.com/forms/d/1oGAdU-pJO9SQ4hLMa-Lj4XXcRWBf4aTwgmZxSEmwE20/edit?ts=61e5537a#responses](url)
