### ISSUE TITLE
Details for user screen

### ISSUE THREAD

**Issue by thuymymai** [minhson0506/DatingApp-Hook#21]

**Comment by thuymymai** [comment]
![Screenshot 2022-02-18 at 0 04 09](https://user-images.githubusercontent.com/85672212/154578505-04254726-2116-46a4-be94-4191d90aedf0.png)
No bottom nav bar for this screen.
Needing fetch owner

**Comment by thuymymai** [comment]
Need fetching owner

**Comment by minhson0506** [comment]
Need review? which branch on it?
