### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by minhson0506** [minhson0506/DatingApp-Hook#4]
Personas are fictional characters, which we create based upon our research in order to represent the different user types/groups that might use our product.
Template: [https://xtensio.com/user-persona-template/](here)

**Comment by thuymymai** [comment]
![Screenshot 2022-01-24 at 9 33 19](https://user-images.githubusercontent.com/85672212/150740324-4ac7b615-e25c-47d3-aac8-3cf76b5df4cc.png)

**Comment by thuymymai** [comment]
![Screenshot 2022-01-24 at 9 36 58](https://user-images.githubusercontent.com/85672212/150740759-d0963f58-de69-43bb-9aca-67d8bd92e98d.png)
