### ISSUE TITLE
Bugs needed fixing

### ISSUE THREAD

**Issue by thuymymai** [minhson0506/DatingApp-Hook#45]
- [x] Remove animated splash screen @thuymymai 
- [x] Change to use Token in main context. @minhson0506 
- [x] Fix buttons border in login page. @thuymymai 
- [x] Fix token missing in register page. @minhson0506 
- [x] Excessive number of pending callback when loading Home. @minhson0506 
- [x] Unmount component in loadMedia. @minhson0506 
- [x] Handle error when this login user already liked other users in Home. @minhson0506 
- [x] Check loading performance. @minhson0506 
- [x] Fix styling in preference and edit profile page according to Ulla. @thuymymai 
- [x] Fix styling in single and profile if Interest is larger than one line. @thuymymai 
- [x] Fix color for search bar in Search screen. @thuymymai 
- [x]  Fix navigation for Interests screen. @thuymymai 
- [x] Add back to top button when listitem is long in Profile. @thuymymai 
- [x] No native splash screen registered for given view controller warning in Interest screen. @minhson0506 
- [x] Handle Alert for Upload when loading & animation finished. @minhson0506 
- [x] Fixed check likes for all files in match screen @thuymymai 
- [x] Display "not found" text when there is no search result @thuymymai 
- [ ] Excessive number of pending callback in Upload and in Home. @minhson0506 
- [x] First registered user after upload cannot reload to see pictures in Profile. @minhson0506 
- [x] Make MyFileOnly not swipe
- [x] Check zIndex on Android
- [x] Check responsive
- [x] Disable delete image in single
- [x] Make search both uppercase and lowercase
- [x] handle wrong email or password in login 
- [x] when new user register, mediaArray is not automatically updated
- [x] new user see herself in home LOL
- [ ] Make listitem back to original position after press button in swipe
- [x] reset Search when not focus
- [ ] Make users cannot like themselves
- [x] scollview in account and fix warning
- [x] keyboard avoiding view and hide keyboard for every screen with input
- [x] display job
- [x] display religion
- [x] display no match found when there is no user after filter
- [x] fix match screen him/her text

**Comment by minhson0506** [comment]
Fixbug will be updated in branch feature/fixBugApp

**Comment by minhson0506** [comment]
Second part of fixbug in branch feature/likeUser

**Comment by thuymymai** [comment]
New tasks after demo:

- [ ] Fix swipe and press in Home
- [ ] Icons in Profile sometimes not responsive
- [ ] Search for username
- [ ] Back to top in Like screen
