### ISSUE TITLE
App Presentation 

### ISSUE THREAD

**Issue by thuymymai** [minhson0506/DatingApp-Hook#49]

**Comment by JulianCCY** [comment]
[https://docs.google.com/presentation/d/1kuEn2BktrD__yekDRm6SKBdzVMysyIMWUZh4W0bhGrI/edit?usp=sharing](slide)

**Comment by JulianCCY** [comment]
[Slide](https://docs.google.com/presentation/d/1kuEn2BktrD__yekDRm6SKBdzVMysyIMWUZh4W0bhGrI/edit?usp=sharing)

**Comment by thuymymai** [comment]
Done yayy
