### ISSUE TITLE
UI resources 

### ISSUE THREAD

**Issue by JulianCCY** [minhson0506/DatingApp-Hook#9]
### Bottom Navigation:
- [bottom navigation(react-native-paper)](https://callstack.github.io/react-native-paper/bottom-navigation.html)
### Like and rating
- [Like Animation(framer)](https://www.framer.com/examples/like-animation/)
- [Like Counter](https://www.framer.com/examples/like-counter/)
- [Star rating(Wanda)](https://design.wonderflow.ai/components/other/star-meter)
- [Star rating(framer)](https://www.framer.com/examples/star-rating/)
### Loading
- [Loading spinner(Wanda)](https://design.wonderflow.ai/components/loading/spinner)
- [Loading Indicator(framer)](https://www.framer.com/examples/loading-indicator/)
### Login page
- [Login/Register Tab(Wanda)](https://design.wonderflow.ai/components/navigation/tab)
- [Show password(framer)](https://www.framer.com/examples/show-password/)

### Geographical location
- [Slider for choosing distance(Wanda)](https://design.wonderflow.ai/components/inputs/slider)
- [Slider for choosing distance(Framer)](https://www.framer.com/examples/slider/)
- [Map(framer)](https://www.framer.com/examples/map/)
### Card
- [Card List(framer)](https://www.framer.com/examples/card-list/)
- [Perspective Tilt for card](https://www.framer.com/examples/perspective-tilt/)
### Alert message
- [Toast Prompt for alert message(framer)](https://www.framer.com/examples/toast-prompt/)
### Others
- [Dropdown(Wanda)](https://design.wonderflow.ai/components/dialogs/dropdown)
- [SVG Animation(framer)](https://www.framer.com/examples/svg-animation/)
- [Card Swipe(framer)](https://www.framer.com/examples/card-swipe/)

**Comment by thuymymai** [comment]
Icons packs: [https://www.flaticon.com/premium-icon/up-arrow_3840824?related_id=3840824&origin=pack](https://www.flaticon.com/premium-icon/up-arrow_3840824?related_id=3840824&origin=pack)

**Comment by thuymymai** [comment]
Swipe card: [https://github.com/tarasvakulka/react-native-cards-swipe](https://github.com/tarasvakulka/react-native-cards-swipe)
